[toolchain]
anchor_version = "0.32.1"

[features]
seeds = false
skip-lint = false

[programs.devnet]
liilend = "BrtmpQXVMryfdrtTQLxFaJtSTa78nULPuxJcQfFznpQc"

[programs.mainnet]
liilend = "BrtmpQXVMryfdrtTQLxFaJtSTa78nULPuxJcQfFznpQc"

[programs.localnet]
liilend = "BrtmpQXVMryfdrtTQLxFaJtSTa78nULPuxJcQfFznpQc"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[test]
startup_wait = 15000

[scripts]
deploy-devnet = "anchor build --program-name liilend && anchor deploy --program-name liilend --provider.cluster devnet"
